FROM node:12-alpine

RUN apk add --no-cache \
        bash \
        python3 \
        py3-pip \
    && pip3 install --upgrade pip \
    && pip3 install \
        awscli \
    && rm -rf /var/cache/apk/*

RUN mkdir /src
WORKDIR /src
ADD . /src/

RUN npm install
