# TEMP:
# NOTE: Keep in case we need to switch out multi-stage build for
# async pdf build

version: '3.1'

services:
  docs:
    depends_on:
      - pdf
      - nginx
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        nginx_conf: ./docker/nginx.conf
    #ports:
    #  - "3000:80"
    #  - "3443:443"
    volumes:
      - build:/src
    links:
      - "pdf:pdf"
  pdf:
    depends_on:
      - nginx
    image: openlabs/docker-wkhtmltopdf-aas
    volumes:
      #- ../:/tmp/pdf
      - build:/tmp/pdf
    #ports:
    # - "8002:80"
  nginx:
    image: nginx
    volumes:
      - build:/src
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
      - "3443:443"
  #link_checker:
  #  volumes:
  #    - build:/src

volumes:
  build: