#
# Build MS PDF
#

FROM node:8.1.2-slim as ms-pdf-builder

ARG git_branch

RUN apt-get update -qq
RUN apt-get install -y build-essential
RUN apt-get install -y ghostscript

RUN mkdir /src
WORKDIR /src
ADD . /src/

RUN npm install

RUN make build-swagger
RUN make build-ngindox

RUN \
GIT_BRANCH=$git_branch \
npm run build-pdf

#
# Build PDF
#
FROM ubuntu:14.04
RUN apt-get update

RUN apt-get install -y wget parallel && \
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - && \
echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list && \
apt-get update && \
apt-get install -y google-chrome-stable

RUN mkdir -p /tmp/pdf
WORKDIR /tmp/pdf

COPY --from=ms-pdf-builder /src ./

RUN make build-pdf-production

#
# Concat PDF
#

FROM ms-pdf-builder as pdf-concat

RUN mkdir /src/build-pdf

WORKDIR /src
COPY --from=pdf-builder /tmp/pdf/build-pdf ./build-pdf

RUN make build-pdf-concat-production
