version: '3.1'

services:
  docs:
    image: mesosphere/dcos-docs-site
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.docs
      args:
        nginx_dir: ./docker/nginx
        git_branch: ${GIT_BRANCH}
        algolia_update: ${ALGOLIA_UPDATE}
        algolia_project_id: ${ALGOLIA_PROJECT_ID}
        algolia_public_key: ${ALGOLIA_PUBLIC_KEY}
        algolia_private_key: ${ALGOLIA_PRIVATE_KEY}
        algolia_index: ${ALGOLIA_INDEX}
        algolia_clear_index: ${ALGOLIA_CLEAR_INDEX}
        algolia_skip_sections: ${ALGOLIA_SKIP_SECTIONS}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - build:/src/build
      - build-pdf:/src/build-pdf
  pdf:
    image: openlabs/docker-wkhtmltopdf-aas
    volumes:
      - ../:/tmp/pdf
    ports:
     - "8002:80"
volumes:
  build:
    driver_opts:
      type: none
      device: ${PWD}/build
      o: bind
  build-pdf:
