# Usage:
# $ cd dcos-docs-site
# $ docker build -t dcos-docs-site -f ./docker/Dockerfile.dev .
# $ docker run --net=host -v `pwd`:/src -ti dcos-docs-site make build-ngindox
# $ docker run --net=host -v `pwd`:/src -ti dcos-docs-site npm run dev
#
# For extra fast building, delete stuff under ./pages/ that you're not interested in:
# rm -rf ./pages/services
# rm -rf ./pages/1.7
# rm -rf ./pages/1.8
# rm -rf ./pages/1.9
# $ docker run --net=host -v `pwd`:/src -ti dcos-docs-site make build-ngindox
# $ docker run --net=host -v `pwd`:/src -ti dcos-docs-site npm run dev
#
# Then when you're done, `git checkout ./pages` again
FROM node:8.1.2-slim

RUN apt-get update -qq
RUN apt-get install -y build-essential

EXPOSE 3000

WORKDIR /src

# Only render files matching the following pattern
# docker build -t dcos-docs-site -f docker/Dockerfile.dev .
# docker run -ti -e RENDER_PATH_PATTERN=services/myservice/1.2.3/** -p 3000 dcos-docs-site
ENV RENDER_PATH_PATTERN **
