# TEMP:
# NOTE: Keep in case we need to switch out multi-stage build for
# async pdf build

#
# Build
#

FROM node:8.1.2-slim as builder

RUN apt-get update -qq && apt-get install -y build-essential

RUN mkdir /src
VOLUME ['/src']
WORKDIR /src
ADD . /src/

RUN npm install -g bootprint
RUN npm install -g bootprint-openapi
RUN npm install -g ngindox
RUN npm install

#RUN make clean
#RUN make build

ENTRYPOINT ["/bin/bash", "-c", "make build"]

# Debug
RUN pwd
RUN ls ./

#
# Nginx
#

#FROM nginx:latest

#ARG nginx_conf

#RUN mkdir -p /src/build
#RUN mkdir -p /src/build-pdf

#WORKDIR /src/build
#COPY --from=builder /src/build ./

#WORKDIR /src/build-pdf
#COPY --from=builder /src/build-pdf ./

#ADD "$nginx_conf" /etc/nginx/conf.d/default.conf
#RUN service nginx restart

#EXPOSE 80
#EXPOSE 443
