FROM node:12-alpine3.13

RUN apk add --no-cache \
        bash \
        python3 \
        py3-pip \
    && pip3 install --upgrade pip \
    && pip3 install \
        awscli \
    && rm -rf /var/cache/apk/*

RUN mkdir /src
WORKDIR /src

RUN mkdir /npm
ADD package.json /npm/
RUN cd /npm && npm install

ADD . /src/
RUN ln -s /npm/node_modules /src/node_modules
