FROM node:gallium-buster-slim

RUN apt-get -y update && apt-get install -y python \
        bash \
        python3 \
        python3-pip \
    && pip3 install --upgrade pip \
    && pip3 install \
        awscli \
    && rm -rf /var/cache/apk/* && apt-get clean

RUN mkdir /src
WORKDIR /src

RUN mkdir /npm
ADD package.json package-lock.json /npm/
RUN cd /npm && npm install

ADD . /src/
RUN ln -s /npm/node_modules /src/node_modules
