extends: existence
message: "Don't use '%s'."
link: https://docs.microsoft.com/en-us/style-guide
ignorecase: true
level: error
tokens:
  - abortion
  - and so on
  - app developer
  - app(?:lication)? file
  - application developer
  - application program
  - applications developer
  - as well as
  - backbone
  - backend
