extends: existence
message: "Use an en dash in a range of numbers."
link: https://docs.microsoft.com/en-us/style-guide/numbers
nonword: true
level: suggestion
action:
  name: edit
  params:
    - replace
    - '-'
    - '–'
tokens:
  - '\b\d+\s?[-]\s?\d+\b'
