apiVersion: v1
kind: ConfigMap
metadata:
  name: config-artifact-bucket
  labels:
    dispatch.d2iq.io/catalog: "true"
data:
  location: s3://{{ .Values.minio.defaultBucket.name }}
  bucket.service.account.secret.name: s3-config
  bucket.service.account.secret.key: boto
  bucket.service.account.field.name: BOTO_CONFIG
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.minio.service.name }}
spec:
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
    release: {{ .Release.Name }}
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-config
  labels:
    dispatch.d2iq.io/catalog: "true"
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.minio.accessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.secretKey }}
  ENDPOINT: {{ .Values.minio.service.name }}.{{ .Release.Namespace }}
  credentials: |
    [default]
    aws_access_key_id = {{ .Values.minio.accessKey }}
    aws_secret_access_key = {{ .Values.minio.secretKey }}
  boto: |
    [Boto]
    is_secure=False

    [Credentials]
    aws_access_key_id = {{ .Values.minio.accessKey }}
    aws_secret_access_key = {{ .Values.minio.secretKey }}

    [s3]
    host = {{ .Values.minio.service.name }}.{{ .Release.Namespace }}
    calling_format = boto.s3.connection.OrdinaryCallingFormat
