{{- $fullName := include "dispatch.fullname" . -}}
{{- $eventSinkLabels := include "dispatch.event-sink.labels" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-event-sink-{{ sha256sum $eventSinkLabels | trunc 7 }}
  labels:
    {{- nindent 4 $eventSinkLabels }}
spec:
  selector:
    matchLabels:
      {{- nindent 6 $eventSinkLabels }}
  template:
    metadata:
      labels:
        {{- nindent 8 $eventSinkLabels }}
    spec:
      serviceAccountName: {{ $fullName }}-event-sink
      containers:
      - name: event-sink
        image: {{ .Values.dispatch.image }}
        imagePullPolicy: {{ .Values.dispatch.pullPolicy }}
        args:
        - component
        - event-sink
        - --output=
        - --namespace={{ $.Release.Namespace }}
        - --use-cache=true
        {{- with .Values.dispatch.dashboardUrl }}
        - --dashboard-url={{ . }}
        {{- end }}
        {{- with .Values.dispatch.watchNamespaces }}
        {{- range $namespace := . }}
        - --watch-namespace={{ $namespace }}
        {{- end }}
        {{- end }}
        {{- with .Values.eventSink.defaultStepResources }}
        - --default-step-resources={{ toJson . }}
        {{- end }}
        {{- with .Values.eventSink.resources }}
        resources:
          {{ toYaml . | nindent 10 | trim }}
        {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullName }}-event-sink
---
{{ if .Values.dispatch.watchNamespaces }}
{{ range $namespace := .Values.dispatch.watchNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullName }}-event-sink
  namespace: {{ $namespace }}
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelineresources
  - pipelineruns
  - pipelines
  - tasks
  - taskruns
  verbs:
  - create
  - watch
  - get
  - list
  - patch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dispatch.d2iq.io
  resources:
  - repositories
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - get
  - list
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullName }}-event-sink
  namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullName }}-event-sink
subjects:
- kind: ServiceAccount
  name: {{ $fullName }}-event-sink
  namespace: {{ $.Release.Namespace }}
---
{{ end }}
{{ else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $fullName }}-event-sink
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelineresources
  - pipelineruns
  - pipelines
  - tasks
  - taskruns
  verbs:
  - create
  - watch
  - get
  - list
  - patch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dispatch.d2iq.io
  resources:
  - repositories
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - get
  - list
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $fullName }}-event-sink
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $fullName }}-event-sink
subjects:
- kind: ServiceAccount
  name: {{ $fullName }}-event-sink
  namespace: {{ $.Release.Namespace }}
---
{{ end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-event-sink
  labels:
    {{- nindent 4 $eventSinkLabels }}
spec:
  selector:
    {{- nindent 4 $eventSinkLabels }}
  ports:
  - protocol: TCP
    port: 9300
    targetPort: 9300
---
{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dispatch
  labels:
    {{- include "dispatch.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
  - hosts:
    {{- range .hosts }}
    - {{ . | quote }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ . }}
        backend:
          serviceName: {{ $fullName }}-event-sink
          servicePort: 9300
      {{- end }}
  {{- end }}
{{- end }}
---
{{- if .Values.global.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullName }}-event-sink
  labels:
    release: {{ .Values.global.prometheus.release }}
spec:
  endpoints:
  - path: /metrics
  namespaceSelector:
    matchNames:
    - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      {{- nindent 6 $eventSinkLabels }}
{{- end }}
