{{- $fullName := include "dispatch.fullname" . -}}
{{- $releaseNamespace := .Release.Namespace }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $fullName }}-garbage-collector
  labels:
    component: garbage-collector
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ $releaseNamespace }}-garbage-collector
          containers:
          - name: garbage-collector
            image: {{ .Values.dispatch.image }}
            imagePullPolicy: {{ .Values.dispatch.pullPolicy }}
            args:
            - component
            - garbage-collect
            - --namespace={{ $releaseNamespace }}
            {{- with .Values.dispatch.watchNamespaces }}
            {{- range $namespace := . }}
            - --watch-namespace={{ $namespace }}
            {{- end }}
            {{- end }}
            {{- if .Values.dispatch.garbageCollectAge }}
            - --age={{ .Values.dispatch.garbageCollectAge}}
            {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $releaseNamespace }}-garbage-collector
---
{{ if .Values.dispatch.watchNamespaces }}
{{ range $namespace := .Values.dispatch.watchNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $releaseNamespace }}-garbage-collector
  namespace: {{ $namespace }}
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelineresources
  - pipelineruns
  - pipelines
  - tasks
  - taskruns
  verbs:
  - watch
  - get
  - list
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $releaseNamespace }}-garbage-collector
  namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $releaseNamespace }}-garbage-collector
subjects:
- kind: ServiceAccount
  name: {{ $releaseNamespace }}-garbage-collector
  namespace: {{ $releaseNamespace }}
---
{{ end }}
{{ else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $releaseNamespace }}-garbage-collector
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelineresources
  - pipelineruns
  - pipelines
  - tasks
  - taskruns
  verbs:
  - watch
  - get
  - list
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $releaseNamespace }}-garbage-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $releaseNamespace }}-garbage-collector
subjects:
- kind: ServiceAccount
  name: {{ $releaseNamespace }}-garbage-collector
  namespace: {{ $releaseNamespace }}
---
{{ end }}
