apiVersion: v1
kind: ServiceAccount
metadata:
  name: dispatch-generate-pipeline
  labels:
    dispatch.d2iq.io/catalog: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dispatch-generate-pipeline
  labels:
    dispatch.d2iq.io/catalog: "true"
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelineresources
  - pipelineruns
  - pipelines
  - tasks
  - taskruns
  verbs:
  - create
  - watch
  - get
  - list
  - patch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dispatch.d2iq.io
  resources:
  - repositories
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - get
  - list
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dispatch-generate-pipeline
  labels:
    dispatch.d2iq.io/catalog: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dispatch-generate-pipeline
subjects:
- kind: ServiceAccount
  name: dispatch-generate-pipeline
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: generate-pipeline
  labels:
    dispatch.d2iq.io/catalog: "true"
spec:
  inputs:
    params:
      - name: dashboardurl
        type: string
        description: The tekton dashboard URL
      - name: request
        type: string
        description: The raw request as string
      - name: taskrun
        type: string
        description: The name of the generate-pipeline taskrun
      - name: defaultstepresources
        type: string
        description: The default resources to allocate for steps
  steps:
  - name: generate-pipeline
    image: "{{ .Values.dispatch.image }}"
    imagePullPolicy: {{ .Values.dispatch.pullPolicy }}
    env:
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
    command:
    - /ko-app/dispatch
    args:
    - component
    - generate-pipeline
    - --dashboard-url
    - $(inputs.params.dashboardurl)
    - --request
    - $(inputs.params.request)
    - --taskrun
    - $(inputs.params.taskrun)
    - --default-step-resources
    - $(inputs.params.defaultstepresources)
    - --namespace=$(NAMESPACE)
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
