{{- if not (.Capabilities.APIVersions.Has "dispatch.d2iq.io/v1alpha1") }}
{{.Files.Get "crds/dispatch.yaml" }}
{{- end }}
---
{{- if not (.Capabilities.APIVersions.Has "argoproj.io/v1alpha1") }}
{{.Files.Get "crds/argocd.yaml" }}
{{- end }}
---
{{- if not (.Capabilities.APIVersions.Has "tekton.dev/v1alpha1") }}
{{.Files.Get "crds/tekton.yaml" }}
{{- end }}
---
{{- if not (.Capabilities.APIVersions.Has "dashboard.tekton.dev/v1alpha1") }}
{{.Files.Get "crds/tekton-dashboard.yaml" }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dispatch-crds
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  dispatch.yaml: |
{{.Files.Get "crds/dispatch.yaml" | indent 6}}
  argocd.yaml: |
{{.Files.Get "crds/argocd.yaml" | indent 6}}
  tekton.yaml: |
{{.Files.Get "crds/tekton.yaml" | indent 6}}
  tekton-dashboard.yaml: |
{{.Files.Get "crds/tekton-dashboard.yaml" | indent 6}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dispatch-crds
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dispatch-crds
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dispatch-crds
subjects:
  - kind: ServiceAccount
    name: dispatch-crds
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dispatch-crds
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
---
apiVersion: batch/v1
kind: Job
metadata:
  name: dispatch-crds
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    spec:
      serviceAccountName: dispatch-crds
      containers:
        - name: dispatch-crds
          image: "bitnami/kubectl:1.16.2"
          volumeMounts:
            - name: dispatch-crds
              mountPath: /etc/dispatch-crds
              readOnly: true
          command: ["kubectl", "apply", "-f", "/etc/dispatch-crds"]
      volumes:
        - name: dispatch-crds
          configMap:
            name: dispatch-crds
      restartPolicy: OnFailure
