{{ if .Values.dispatch.watchNamespaces }}
{{ $releaseNamespace := .Release.Namespace }}
{{ range $namespace := .Values.dispatch.watchNamespaces }}
{{ if ne $namespace $releaseNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace }}
---
{{ end }}
{{ end }}
{{ end }}
