name: Cleanup Buckets
on:
  push:
    branches:
      - 'hm/fix-cleanup-buckets-job'
  schedule:
    - cron:  "0 * * * *"
jobs:
  cleanup-buckets:
    permissions:
      contents: read
      id-token: write
    runs-on:
    - ubuntu-latest
    env:
      AWS_DEFAULT_REGION: "us-west-2"
    steps:
    - name: Login to docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.NEXUS_USERNAME }}
        password: ${{ secrets.NEXUS_PASSWORD }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: arn:aws:iam::139475575661:role/dcos-docs-site
        aws-region: us-west-2
    - name: Cleanup Buckets
      run: |
        set -euxo pipefail
        sudo apt-get update && sudo apt-get install jq
        docker run -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION  -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN amazon/aws-cli s3 rb s3://docs-d2iq-com-pr-4684 --force
        bucket_list=$(docker run -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION  -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN amazon/aws-cli s3api list-buckets)        
        buckets=$(echo $bucket_list | jq '.Buckets | .[].Name' -r)
        echo $buckets
      shell: bash    

# buckets=$(docker run -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION  -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN amazon/aws-cli s3api list-buckets | jq '.Buckets | .[].Name' -r | grep "docs-d2iq-com-pr-")
        # bucket_json = echo $bucket_list | jq '.Buckets
        # echo $bucket_json
        # bucket_names = echo $bucket_json | .[].Name' -r
        # echo $bucket_names
        # buckets = echo $bucket_names | grep "docs-d2iq-com-pr-"
        # echo $buckets
        # open_prs=$(docker run curlimages/curl:7.75.0 "https://api.github.com/repos/mesosphere/dcos-docs-site/pulls?state=open" | jq '.[].number')
        # echo $open_prs
        # for bucket in $buckets; do
        #   found=false
        #   for pr in $open_prs; do
        #     if [[ $bucket == *"$pr"* ]]; then
        #       found=true
        #       break
        #     fi
        #   done
        #   if [ "$found" = false ] ; then
        #     docker run -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION  -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN amazon/aws-cli s3 rb s3://$bucket --force
        #   fi
        # done


        # + echo '{' '"Buckets":' '[' '{' '"Name":' '"d2iq-production-logs",' '"CreationDate":' '"2019-08-08T08:05:42+00:00"' '},' '{' '"Name":' '"d2iq-production-tf-state",' '"CreationDate":' '"2020-01-30T17:22:24+00:00"' '},' '{' '"Name":' '"d2iq-sre-misc",' '"CreationDate":' '"2020-09-25T17:07:57+00:00"' '},' '{' '"Name":' '"dcos-versions-lambda-dev-serverlessdeploymentbuck-zzsyjs09jbn1",' '"CreationDate":' '"2020-02-26T09:59:48+00:00"' '},' '{' '"Name":' '"dcos-versions-lambda-pro-serverlessdeploymentbuck-1o7vps536secu",' '"CreationDate":' '"2020-03-26T12:01:03+00:00"' '},' '{' '"Name":' '"docs-d2iq-com-preview",' '"CreationDate":' '"2021-09-06T08:47:13+00:00"' '},' '{' '"Name":' '"docs-d2iq-com-production",' '"CreationDate":' '"2023-02-08T10:37:27+00:00"' '},' '{' '"Name":' '"docs-d2iq-com-staging",' '"CreationDate":' '"2021-12-06T22:44:17+00:00"' '},' '{' '"Name":' '"downloads.d2iq.com",' '"CreationDate":' '"2022-07-01T08:44:48+00:00"' '},' '{' '"Name":' '"downloads.d2iq.com-logs",' '"CreationDate":' '"2022-06-30T10:48:35+00:00"' '},' '{' '"Name":' '"eng-production-prow-app-s3-bucket-april8",' '"CreationDate":' '"2020-04-09T01:29:58+00:00"' '},' '{' '"Name":' '"eng-production-prow-konvoy-s3-bucket-april3",' '"CreationDate":' '"2020-04-06T22:12:52+00:00"' '},' '{' '"Name":' '"kaptain.downloads.d2iq.com",' '"CreationDate":' '"2021-07-29T18:13:54+00:00"' '},' '{' '"Name":' '"konvoy-prod-cve-reporter",' '"CreationDate":' '"2021-02-18T12:52:16+00:00"' '},' '{' '"Name":' '"konvoy-prod-elastic",' '"CreationDate":' '"2020-06-29T14:38:51+00:00"' '},' '{' '"Name":' '"konvoy-prod-lb-logs",' '"CreationDate":' '"2020-06-29T14:38:44+00:00"' '},' '{' '"Name":' '"konvoy-prod-thanos",' '"CreationDate":' '"2020-07-10T17:34:56+00:00"' '},' '{' '"Name":' '"konvoy-prod-velero",' '"CreationDate":' '"2020-06-29T14:38:51+00:00"' '},' '{' '"Name":' '"konvoy-staging-devx-cac8-cve-reporter",' '"CreationDate":' '"2022-08-26T08:33:57+00:00"' '},' '{' '"Name":' '"konvoy-staging-devx-cac8-elastic",' '"CreationDate":' '"2020-06-22T23:04:27+00:00"' '},' '{' '"Name":' '"konvoy-staging-devx-cac8-lb-logs",' '"CreationDate":' '"2020-06-22T23:04:28+00:00"' '},' '{' '"Name":' '"konvoy-staging-devx-cac8-thanos",' '"CreationDate":' '"2020-07-09T17:11:55+00:00"' '},' '{' '"Name":' '"konvoy-staging-devx-cac8-velero",' '"CreationDate":' '"2020-06-22T23:04:28+00:00"' '},' '{' '"Name":' '"mesosphere-ospo",' '"CreationDate":' '"2019-12-20T09:59:43+00:00"' '},' '{' '"Name":' '"mesosphere-production-logs",' '"CreationDate":' '"2020-07-04T01:09:01+00:00"' '},' '{' '"Name":' '"packages-test.d2iq.com",' '"CreationDate":' '"2019-10-29T17:57:40+00:00"' '},' '{' '"Name":' '"packages.d2iq.com",' '"CreationDate":' '"2022-05-26T20:06:08+00:00"' '},' '{' '"Name":' '"repos.mesosphere.com",' '"CreationDate":' '"2022-08-24T16:16:56+00:00"' '},' '{' '"Name":' '"terraform-state-eng-production",' '"CreationDate":' '"2020-06-09T11:11:56+00:00"' '},' '{' '"Name":' '"terraform-state-eng-production-demo",' '"CreationDate":' '"2020-09-02T17:34:48+00:00"' '}' '],' '"Owner":' '{' '"DisplayName":' '"aws+production",' '"ID":' '"cdbdb462efe94504da77363fbd9a5c4fbbb844404fe6b957c953616dd979a47f"' '}' '}'