name: Main
on: [ pull_request ]
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Login to docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Pull image
      run: docker pull mesosphere/docs:latest
    - name: Build image
      run: cp docker/Dockerfile.production.dockerignore .dockerignore
      run: docker build --cache-from mesosphere/docs:latest -f docker/Dockerfile.production -t mesosphere/docs:latest .