name: Main
on: [ pull_request ]
jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      IS_MAIN: ${{ github.head_ref == main }}
      IS_BETA: ${{ github.head_ref == beta }}
      IS_BRANCH: ${{ github.head_ref == hm/add-main-workflow }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Pull image
      run: docker pull mesosphere/docs:latest
    - name: Build image
      run: |
        cp docker/Dockerfile.production.dockerignore .dockerignore
        docker build --cache-from mesosphere/docs:latest -f docker/Dockerfile.production -t mesosphere/docs:latest .
    - name: Build & Deploy Preview Docs
      run: |
        echo $IS_MAIN
        echo $IS_BETA
        echo $IS_BRANCH
      shell: bash