name: Main
on: [ pull_request ]
jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      branch: ${{ github.head_ref }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Pull image
      run: docker pull mesosphere/docs:latest
    - name: Build image
      run: |
        cp docker/Dockerfile.production.dockerignore .dockerignore
        docker build --cache-from mesosphere/docs:latest -f docker/Dockerfile.production -t mesosphere/docs:latest .
    - name: Build & Deploy Preview Docs
      run: |
        if [ "$branch" != "beta" ]; then
          echo "Run non beta code"        
        fi
      shell: bash