swagger: '2.0'
info:
  version: '1.0.0'
  title: DC/OS GUI Update Service
  description: ' '
host: ..
basePath: /
schemes:
- http
consumes:
- application/json
paths:
  /v1/version/:
    get:
      description: Returns metadata for the current DC/OS GUI version.
      summary: DC/OS GUI version metadata
      tags:
      - information
      operationId: getUIVersionMetadata
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '#/definitions/VersionMetadata'
        500:
          description: Internal service error getting version metadata.
  /v1/update/{version}/:
    post:
      description: Initiate an update of the DC/OS GUI to the universe package version provided.
      summary: Update DC/OS GUI
      tags:
      - update
      operationId: updateDCOSUIVersion
      produces:
      - text/plain
      parameters:
      - name: version
        in: path
        description: DC/OS GUI package version number to update to. A list of all available DC/OS GUI packages can be retrieved from the Cosmos API `/package/list-versions/`.
        required: true
        type: string
      responses:
        200:
          description: DC/OS GUI updated successfully.
          schema:
            type: string
          examples:
            text: Update to 1.0.0 completed.
        202:
          description: Accepted - An update to the version you requested is already in progress
          schema:
            type: string
          examples:
            text: Service is currently processing an update request
        400:
          description: Bad request
          schema:
            type: string
          examples:
            text: The requested version is not available.
        409:
          description: Conflict - The service is currently processing an update to a different version than requested, or a reset to the default DC/OS GUI version.
          schema:
            type: string
          examples:
            text: Service is currently processing an update request to 1.1.0.
        500:
          description: Unexpected error processing DC/OS GUI update.
          schema:
            type: string
          examples:
            text: Could not find DC/OS GUI-bundle asset in package details.
  /v1/reset/:
    delete:
      tags:
      - update
      summary: Reset DC/OS GUI
      description: Reset DC/OS GUI to the default version.
      operationId: resetDCOSUIVersion
      produces:
      - text/plain
      parameters: []
      responses:
        200:
          description: DC/OS GUI version reset was successful.
        409:
          description: Conflict - DC/OS GUI version cannot be reset while an update or another reset is currently in progress.
        500:
          description: Unexpected error processing DC/OS GUI version reset.
definitions:
  VersionMetadata:
    title: VersionMetadata
    type: object
    properties:
      default:
        type: boolean
        description: The current DC/OS GUI is the default version.
        example: false
      packageVersion:
        type: string
        description: The DC/OS GUI package version as found in {{ model.packageRepo }}. This is usually a semantic version, or 'Default' if the current DC/OS GUI is the default.
        example: 1.0.0
      buildVersion:
        type: string
        description: This is the fully qualified build version for the current DC/OS GUI.
        example: master+v1.0.0